import Head from "next/head";
import Navbar from "../../components/shared/navbar";
import Topbar from "../../components/shared/topbar";
import SingleCategory from "../../components/SingleCategory/shop";

function Shop() {
  return (
    <div>
      <Head>
        <title>Covid Ecommerce Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Navbar />
      <SingleCategory />
    </div>
  );
}

export default Shop;
