import Head from "next/head";
import { useForm } from "react-hook-form";
import Navbar from "../../components/shared/Navbar";
import Topbar from "../../components/shared/Topbar";
import { Container } from "../../components/styles/Container.styled";
import { FlexCenter } from "../../components/styles/Flex.styled";

const Login = () => {

    const {
        register,
        handleSubmit,
        watch,
        formState: { errors }
    } = useForm();

    const onSubmit = (data) => {
        console.log(data);
    }; // your form submit function which will invoke after successful validation

    console.log(watch("example"));

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar></Topbar>
            <Container>
                <Navbar></Navbar>

                <FlexCenter>

                    <form onSubmit={handleSubmit(onSubmit)}>
                        {/* register your input into the hook by invoking the "register" function */}
                        <input defaultValue="test" {...register("example")} />
                        <br></br>

                        {/* include validation with required or other standard HTML validation rules */}
                        <input {...register("exampleRequired", { required: true })} />
                        {/* errors will return when field validation fails  */}
                        {errors.exampleRequired && <p>This field is required</p>}
                        <br></br>

                        <input type="submit" />
                    </form>

                </FlexCenter>

            </Container>

        </>
    );
};

export default Login;