import Head from "next/head";
import { useForm } from "react-hook-form";
import Navbar from "../../components/shared/navbar";
import Topbar from "../../components/shared/topbar";
import { AuthBox, Container } from "../../components/styles/Container.styled";
import { Flex, FlexCenter } from "../../components/styles/Flex.styled";
import ButtonInput from "../../components/UI/ButtonInput";
import TextInput from "../../components/UI/TextInput";
import { BsArrowRight } from 'react-icons/bs';
import styled from "styled-components";
import { Error } from "../../components/UI/Error";
import Link from 'next/link';
import {useStoreActions, useStoreState} from "easy-peasy";
import {useRouter} from "next/router";


const Login = () => {
    const router = useRouter()

    const {
        register,
        handleSubmit,
        formState: { errors }
    } = useForm();

   const {LogIn} = useStoreActions(actions => actions.Auth);

    const onSubmit = async (data) => {
        await LogIn(data) && router.push('/');

    };


    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar/>
            <Container>
                <Navbar/>

                <FlexCenter>

                    <AuthBox onSubmit={handleSubmit(onSubmit)}>
                        <TextInput {...register("email", { required: "Email is Required." })} placeholder="Email" type="text" />
                        {errors.email && <Error>Email or User Name is required</Error>}

                        <TextInput {...register("password", { required: "Password is Required." })} placeholder="Password" type="password" />
                        {errors.password && <Error>Password is required</Error>}

                        <ButtonInput type="submit" value={`LOGIN`} />
            
                        <FlexCenter>
                            <p style={{ fontSize: '16px' }}>Don't have an account?</p>
                            <Link href="/register">
                                <a style={{ fontSize: '16px', marginLeft: '5px' }}>Register</a>
                            </Link>
                        </FlexCenter>
                    </AuthBox>

                </FlexCenter>

            </Container>

        </>
    );
};

export default Login;