import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { getBrands, getCategories } from "../api/home";
import BrandCards from "../components/brandCard/brands";
import ReviewCards from "../components/reviewCard/reviews";
import Navbar from "../components/shared/navbar";
import Topbar from "../components/shared/topbar";
import Slide from "../components/slider/slides";
import { Container } from "../components/styles/Container.styled";

export default function Home({ saleProducts }) {
  console.log(saleProducts);

  // const { data: saleProd } = useQuery({
  //   queryKey: ['saleProducts'],
  //   queryFn: getProducts,
  //   initialData: saleProducts
  // })
  const { data: categories } = useQuery({
    queryKey: ["categories"],
    queryFn: getCategories,
  });
  const { data: brands } = useQuery({
    queryKey: ["brands"],
    queryFn: getBrands,
  });

  return (
    <>
      <Head>
        <title>Covid Ecommerce Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Navbar categories={categories} />
      <Container>
        <Slide />
        <BrandCards brands={brands} />
        {/* <ProductCards products={saleProd} /> */}
        <ReviewCards />
      </Container>
    </>
  );
}

// export const getStaticProps = async () => {
//   try {
//     const saleProducts = await getProducts();
//     return {
//       props: { saleProducts }, // will be passed to the page component as props
//     };
//   } catch (error) {
//     console.log(error);
//   }

//   // console.log(posts)
// };
