import Head from "next/head";
import BrandCards from "../components/brandCard/brands";
import ProductCards from "../components/productCard/products";
import ReviewCards from "../components/reviewCard/reviews";
import Slide from "../components/slider/slides";
import Topbar from "../components/shared/topbar";
import { Container } from "../components/styles/Container.styled";
import Navbar from "../components/shared/navbar";
import { getCategories, getProducts } from "../api/home";
import { useQuery } from "@tanstack/react-query";


export default function Home({saleProducts}) {
  console.log(saleProducts)

  const { data:saleProd } = useQuery({ queryKey: ['saleProducts'], queryFn: getProducts, initialData: saleProducts })
  const {data:categories } = useQuery({queryKey:['categories'],queryFn:getCategories})

  return (
    <>
    <Head>
          <title>Covid Ecommerce Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <Topbar />
      <Navbar categories= {categories} />
      <Container>
        
        <Slide />
        <BrandCards />
        <ProductCards products={saleProd}/>
        <ReviewCards />
      </Container>
    </>
  );
}










export const getStaticProps = async ( ) => {
    const saleProducts = await getProducts()
    return {
      props: {saleProducts}, // will be passed to the page component as props
    }
    // console.log(posts)
}