import Head from 'next/head'
import Brand from '../components/Brand'
import Product from '../components/Product'
import Review from '../components/Review'
import Slide from '../components/slides'
import Topbar from '../components/shared/Topbar'
import { Container } from '../components/styles/Container.styled'
import Navbar from '../components/shared/Navbar'

export default function Home() {
  return (
    <>
      <Topbar></Topbar>
      <Navbar></Navbar>
      <Container>
        <Head>
          <title>Covid Ecommerce Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <Slide></Slide>
        <Brand></Brand>
        <Product></Product>
        <Review></Review>

      </Container>
    </>
  )
}
