import {useQuery} from '@tanstack/react-query';
import Head from 'next/head';
import {useRouter} from 'next/router';
import {getAllProducts, getSingleProduct} from '../../api/singleProduct';
import SingleProductCard from '../../components/productCard/singleProduct';
import Footer from '../../components/shared/footer/footer';
import GlobalCart from '../../components/shared/globalCart/GlobalCart';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import {Container} from '../../components/styles/Container.styled';

const SingleProduct = ({product}) => {
  const route = useRouter ();
  const slug = route.query.slug;

  const {data: Product, isLoading} = useQuery ({
    queryKey: ['singleProduct', slug],
    queryFn: () => getSingleProduct (slug),
    initialData: product,
  });

  if (isLoading) {
    return <LoadingSkeleton />;
  }

  return (
    <>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Container>
        <Navbar />
        <SingleProductCard product={Product[0]} />
      </Container>
      <GlobalCart />
      <Footer />

    </>
  );
};

export default SingleProduct;

export const getStaticProps = async ({params}) => {
  const slug = params.slug;
  const product = await getSingleProduct (slug);
  return {
    props: {product}, // will be passed to the page component as props
  };
};

export const getStaticPaths = async ({}) => {
  const Products = await getAllProducts ();
  const paths = Products.map (product => ({
    params: {slug: product.attributes.slug},
  }));
  return {
    paths,
    fallback: true,
  };
};
