import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import {useRouter} from 'next/router';
import React from 'react';
import { getFilterdProducts } from '../../api/home';
import ProductCards from '../../components/productCard/products';
import Navbar from '../../components/shared/navbar';
import Topbar from '../../components/shared/topbar';
import { Container } from '../../components/styles/Container.styled';

function Filter () {
  const router = useRouter ();

  const nameTags = router.query.slug?.split ('-');

  let url = '';
  nameTags?.map (tags => {
    url += `filters[$or][0][name][$containsi]=${tags}&`;
  });
  url = url.slice (0 , -1);

  const {data: filteredProducts} = useQuery ({
    queryKey: ['filteredProducts', url],
    queryFn: () => getFilterdProducts (url),
  });

    
    return (
        <>
          
        <Head>
            <title>CheckOut</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Topbar/>
        <Container>
        <Navbar />
        <ProductCards products={filteredProducts}/>
      </Container>

    </>
    )
}

export default Filter;
