import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { getFilterdProducts } from '../../api/home';
import ProductCards from '../../components/productCard/products';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import { Container } from '../../components/styles/Container.styled';


function Filter () {
  const router = useRouter ();

  const nameTags = router.query.slug?.split ('-');

  let url = '';
  nameTags?.map (tags => {
    url += `filters[$or][0][name][$containsi]=${tags}&`;
  });
  url = url.slice (0 , -1);

  const {data: filteredProducts,isLoading} = useQuery ({
    queryKey: ['filteredProducts', url],
    queryFn: () => getFilterdProducts (url),
  });
  

  if (isLoading) {
    return  <LoadingSkeleton/>
  }
    
    return (
        <>
          
        <Head>
            <title>Filtered Product</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Topbar/>
        <Container>
          <Navbar />
          {filteredProducts.length>0?<ProductCards products={filteredProducts} heading={"Filtered Products"} />:<h1 style={{textAlign:'center',margin:"30px"}} >No Products Found</h1>}
                
      </Container>

    </>
    )
}

export default Filter;
