import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { toast } from 'react-toastify';
import { ConfirmOrderPayment } from '../../api/checkout';
import Footer from '../../components/shared/footer/footer';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import { Container } from '../../components/styles/Container.styled';
import { SuccessBox } from '../../components/styles/success.style';


const Success = () => {
  const router = useRouter ();
  const {session_id} = router.query;

  const {data: order, isLoading} = useQuery ({
    queryKey: ['order', session_id],
    queryFn: () => ConfirmOrderPayment(session_id),
    onSuccess:()=> toast('Order Placed Successfully')
  });

  if (isLoading) {
    return <LoadingSkeleton />;
  }
 
  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Container>
        <Navbar />
        {order
          ? <SuccessBox>
              <h2>Your Order Has Been Successfully Placed!</h2>
              <p>Order ID : {order.id} </p>
              <p>Transaction ID : {order.transaction_id}</p>
              <p>Subtotal : {order.sub_total}</p>
              <p>Discount: {order.discount}</p>
              <p>Total : {order.total_price}</p>
              <p>Order Status : Panding</p>
              <p>Payment Status : {order.status}</p>
              <p>Delivery Status : Not yet delivered </p>
            </SuccessBox>
          : ''}

      </Container>
      <Footer />
    </>
  );
};

export default Success;
