import Head from "next/head";
import { useForm } from "react-hook-form";
import Navbar from "../../components/shared/Navbar";
import Topbar from "../../components/shared/Topbar";
import { AuthBox, Container } from "../../components/styles/Container.styled";
import { FlexCenter } from "../../components/styles/Flex.styled";
import ButtonInput from "../../components/UI/ButtonInput";
import TextInput from "../../components/UI/TextInput";
import { BsArrowRight } from 'react-icons/bs';
import styled from "styled-components";
import { Error } from "../../components/UI/Error";
import {AuthBackEndApi} from "../../api/api";
import { useRouter } from 'next/router'
import {useStoreActions} from "easy-peasy";


const Register = () => {
    const router = useRouter()
    const {Register} = useStoreActions(actions => actions.Auth);

    const {
        register,
        handleSubmit,
        watch,
        formState: { errors }
    } = useForm();

    const onSubmit = async (data) => {
        if (data.password !== data.confirmPassword) {
            console.log("Passwords don't match");
        } else {
            await Register(data) && router.push('/');
        }
    }

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar></Topbar>
            <Container>
                <Navbar></Navbar>

                <FlexCenter>

                    <AuthBox onSubmit={handleSubmit(onSubmit)}>

                        <TextInput {...register("name", { required: "Name is Required." })} placeholder="Name" type="text" />
                        {errors.email && <Error>Name is required</Error>}

                        <TextInput {...register("email", { required: "Email is Required." })} placeholder="Email" type="email" />
                        {errors.email && <Error>Email is required</Error>}

                        <TextInput {...register("phone", { required: "Phone is Required." })} placeholder="Phone" type="text"/>
                        {errors.email && <Error>Email is required</Error>}

                        <TextInput {...register("password", { required: "Password is Required." })} placeholder="Password" type="password" />
                        {errors.password && <Error>Password is required</Error>}

                        <TextInput {...register("confirmPassword", { required: "Password is Required." })} placeholder="Confirm Password" type="password" />
                        {errors.password && <Error>Password is required</Error>}

                        <ButtonInput type="submit" value={`Sign Up`} />
                    </AuthBox>

                </FlexCenter>

            </Container>

        </>
    );
};

export default Register;