import {useQuery} from '@tanstack/react-query';
import {Footer} from 'antd/lib/layout/layout';
import Head from 'next/head';
import {useRouter} from 'next/router';
import {getCategories} from '../../api/home';
import {getCategoryProducts} from '../../api/singleCategoryProducts';
import SingleCategory from '../../components/category/category';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import {Container} from '../../components/styles/Container.styled';
import useFilter from '../../hooks/useFilter';

const SingleCatProducts = ({ProductsByCategory}) => {
  const route = useRouter ();
  const categoryName = route.query.category;

  // data:Products will be used in the page to render product list
  const {data: Products, isLoading} = useQuery ({
    queryKey: ['ProductByCat', categoryName],
    queryFn: () => getCategoryProducts (categoryName),
    initialData: ProductsByCategory,
  });

  // filter products by price and categoryName
  const {data, refetch} = useFilter ('category', categoryName, 500, 'asc');

  if (isLoading) {
    return <LoadingSkeleton />;
  }

  return (
    <div>

      <Head>
        <title>Category Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Container>
        <Navbar />
        <SingleCategory
          products={Products}
          heading="Category filter Products"
        />

      </Container>
      <Footer />
    </div>
  );
};

export default SingleCatProducts;

export const getStaticProps = async ({params}) => {
  const categoryName = params.category;
  const ProductsByCategory = await getCategoryProducts (categoryName);
  return {
    props: {ProductsByCategory}, // will be passed to the page component as props
  };
};

export const getStaticPaths = async ({}) => {
  const Category = await getCategories ();
  const paths = Category.map (category => ({
    params: {category: category.attributes.name},
  }));
  return {
    paths,
    fallback: false,
  };
};
