import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { useRouter } from "next/router";
import { getCategories } from "../../api/home";
import { getCategoryProducts } from "../../api/singleCategoryProducts";
import Product from "../../components/productCard/product";
import Navbar from "../../components/shared/navbar";
import Topbar from "../../components/shared/topbar";
import SingleCategory from "../../components/SingleCategory/shop";

const SingleCatProducts = ({ ProductsByCategory }) => {
  const route = useRouter();
  const categoryName = route.query.category;
  console.log("category name", categoryName);
  // data:Products will be used in the page to render product list
  const { data: Products } = useQuery({
    queryKey: ["ProductByCat", categoryName],
    queryFn: () => getCategoryProducts(categoryName),
    initialData: ProductsByCategory,
  });
  console.log("priducts: ", Products);
  return (
    <div>
      <Head>
        <title>Covid Ecommerce Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Navbar />
      <SingleCategory />
      <Product product={Products} />
    </div>
  );
};

export default SingleCatProducts;

export const getStaticProps = async ({ params }) => {
  const categoryName = params.category;
  const ProductsByCategory = await getCategoryProducts(categoryName);
  return {
    props: { ProductsByCategory }, // will be passed to the page component as props
  };
};

export const getStaticPaths = async ({}) => {
  const Category = await getCategories();
  const paths = Category.map((category) => ({
    params: { category: category.attributes.name },
  }));
  return {
    paths,
    fallback: false,
  };
};
