import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { getSingleOrder } from '../../api/order';
import Footer from '../../components/shared/footer/footer';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import { Container } from '../../components/styles/Container.styled';
import { SuccessBox } from '../../components/styles/success.style';

import OrderItemTab from '../../components/table/orderItemsTab';


function OrderDetails() {
    

    const router = useRouter ();
    const {id} = router.query;
  
    const { data: order, isLoading } = useQuery ({
      queryKey: ['order', id],
      queryFn: () => getSingleOrder(id),
    });
  

  
    if (isLoading) {
      return <LoadingSkeleton />;
    }
  
    return (
      <>
        <Head>
          <title>Order Details</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Topbar />
        <Container>
          <Navbar />
          {order?<SuccessBox>
          <h2></h2>
          <p>Order ID : {order.id} </p>
          <p>Transaction ID : {order.attributes.transaction_id}</p>
          <p>Subtotal : {order.attributes.sub_total}</p>
          <p>Discount: {order.attributes.discount}</p>
          <p>Total : {order.attributes.total_price}</p>
           <p>Order Status : {order.attributes.delivery?' Delivered':"Panding" }</p>
          <p>Payment Status : {order.attributes.status}</p>
            <p>Delivery Status : {order.attributes.delivery?' Delivered':' Not yet delivered '} </p>
          </SuccessBox> : null}
          <div>
            <OrderItemTab data={order.attributes.order_items.data} />
          </div>
        </Container>
        <Footer />
      </>
    );
  };
  



export default OrderDetails;
