import {useQuery} from '@tanstack/react-query';
import {useStoreState} from 'easy-peasy';
import Head from 'next/head';
import {useState} from 'react';
import {getOrders} from '../../api/order';
import DashboardCard from '../../components/dashboardCard';
import Footer from '../../components/shared/footer/footer';
import Navbar from '../../components/shared/navbar';
import LoadingSkeleton from '../../components/shared/skeleton';
import Topbar from '../../components/shared/topbar';
import {Container} from '../../components/styles/Container.styled';
import {Cards} from '../../components/styles/dashboard.style';
import Table from '../../components/table';

const Dashboard = () => {
  const {AuthUser} = useStoreState (state => state.Auth);
  let id = AuthUser.id;
  const {data, isLoading} = useQuery ({
    queryKey: ['orders', id],
    queryFn: () => getOrders (id),
  });

  const [field, setField] = useState ();

  if (!id) {
    return <h1 style={{display: 'center'}}> Please Login First</h1>;
  }

  if (isLoading) {
    return <LoadingSkeleton />;
  }

  const total = data.length;
  let pending = 0;
  let delivered = 0;
  const Counter = data.map (v => {
    if (v.attributes.delivered === true) {
      delivered = parseInt (delivered) + 1;
    } else {
      pending = parseInt (pending) + 1;
    }
  });

  let filteredData = [];
  if (field === 'Pending') {
    filteredData = data.filter (u => {
      return u.attributes.delivery === false;
    });
  } else if (field === 'Delivered') {
    filteredData = data.filter (u => {
      return u.attributes.delivery === true;
    });
  } else {
    filteredData = data;
  }

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Container>
        <Navbar />
        <h1> Dashboard</h1>
        <Cards>
          <DashboardCard setField={setField} head="Total" count={total} />

          <DashboardCard
            setField={setField}
            head="Delivered"
            count={delivered}
          />

          <DashboardCard setField={setField} head="Pending" count={pending} />
        </Cards>
        <div>
          {filteredData.length > 0 ? <Table data={filteredData} /> : ''}
        </div>

      </Container>
      <Footer />
    </div>
  );
};

export default Dashboard;
